<a href="https://colab.research.google.com/github/imchihchao/application-of-programming/blob/main/data_analysis_salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = '/content/薪情平臺匯出資料_20250213084325.xlsx'
df = pd.read_excel(url)
df

In [3]:
df = df.drop(columns=['Unnamed: 0'])
df

,Unnamed: 1,礦業及土石採取業,製造業,電力及燃氣供應業,用水供應及污染整治業,營建工程業,批發及零售業,運輸及倉儲業,住宿及餐飲業,出版影音及資通訊業,金融及保險業,不動產業,專業﹑科學及技術服務業,支援服務業,教育業（不含小學以上各級公私立學校等）,醫療保健及社會工作服務業,藝術﹑娛樂及休閒服務業,其他服務業
0,NaN,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計,總計
1,NaN,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值,統計值
2,81年,31937,26942,60937,31017,30825,28152,32272,18209,44519,46380,39911,37285,25708,-,35670,20463,21485
3,82年,32875,28826,64897,33927,33638,30548,34769,18950,48782,50034,42402,39900,27785,-,37176,21124,22150
4,83年,33887,30752,69330,38065,34379,32089,36712,20373,52229,56462,42056,39730,29018,-,39633,22133,23205
5,84年,35633,32494,71940,39072,35278,34149,39260,22317,54649,54658,40614,41436,32927,-,41623,22116,25077
6,85年,37354,33839,79953,39304,35817,34905,40985,22198,55873,56887,40445,41642,33649,-,44797,23532,25846
7,86年,38545,35408,80437,40281,37029,36406,42717,23528,58831,60597,40666,44042,35394,-,47378,24894,26929
8,87年,40083,36438,88192,41708,37886,37696,44076,24040,61421,59546,41719,45393,34814,-,48920,26256,29530
9,88年,41432,37746,91265,44729,38070,38695,45074,25117,61260,60332,44429,47349,34920,-,51020,26524,30825
10,89年,43066,38922,91805,44341,38897,39541,45951,26060,62759,60872,43716,48628,35277,-,53397,27592,31335
11,90年,44068,38420,97399,46002,37746,39775,48019,25973,62100,62657,42277,48812,35579,-,54484,28338,29927
12,91年,44804,38444,93466,43917,36844,39152,46512,25687,59239,65703,40896,45653,34605,-,53841,27889,29236
13,92年,47720,39558,95191,43954,37214,39610,45936,24951,60292,64645,40431,47411,32871,-,55702,27666,28947
14,93年,46307,40666,94525,42880,37916,39819,46884,24812,59417,66671,39781,49292,32707,-,55341,29662,29421
15,94年,47671,41868,91184,47647,38450,39546,48516,25121,61381,65113,38819,50871,32815,-,55604,29898,30384
16,95年,53344,42403,97230,47251,39168,39380,48340,24960,61134,69054,38313,51721,32622,-,55430,31303,30203
17,96年,50949,43240,98519,44399,40310,39463,49095,25476,63738,75824,37874,53144,33102,-,56614,31414,29925
18,97年,51333,43297,89432,44521,40754,39956,49583,26699,63812,71520,40340,54169,32916,-,58134,31931,29314
19,98年,49448,39525,96285,44042,40870,40081,47909,27106,61932,67713,39032,49426,31249,22197,57858,31242,29738
20,99年,52551,43152,96523,45106,41599,41766,49009,27788,64330,74219,42093,52141,32064,22459,57897,32687,30832
21,100年,53978,44603,95382,45828,42716,42562,50330,29715,66376,76920,43783,54097,32855,22416,59900,33236,32526
22,101年,52752,45318,92871,43675,42683,41530,50327,29961,66998,77960,41546,54884,33214,22773,60770,35446,32618
23,102年,54871,45685,88934,44143,42540,41425,49929,30119,65660,77855,42165,53655,33243,22923,61362,36070,33069
24,103年,54093,47455,94111,44919,43251,43119,50142,31225,66613,83071,44786,55169,34177,24226,63750,35829,34556
25,104年,57198,49374,96595,44357,43346,43747,51369,31986,66879,84718,44075,55735,34881,24304,67676,36184,33996
26,105年,55425,49969,94453,43216,42839,43614,52275,31870,68127,85417,42897,55844,35189,24876,69903,36821,33611
27,106年,55339,51853,94764,44170,42506,45568,53204,32896,69466,86395,44840,56874,35669,25287,70612,37522,33987
28,107年,56967,54567,96230,45074,43645,47132,54813,33558,69835,89238,47552,57945,36446,26032,71569,38799,35116
29,108年,58510,55816,96389,45403,44833,48594,55348,34112,71863,93081,50267,62377,36994,30521,65828,39608,35844
30,109年,58585,56538,94761,44913,45622,49087,54834,34496,73631,94557,53937,62949,37240,31068,65278,40685,36564
31,110年,58076,60545,94111,44532,47468,48507,57271,34884,75186,99209,57014,63507,37466,31535,64522,38737,36402
32,111年,60857,63324,96077,45191,48545,49404,61933,36109,78601,100543,56842,65471,37930,32449,66795,40009,38045
33,112年,61765,62492,96596,46328,49477,51159,61957,37662,80434,98243,55337,66841,39193,33433,68516,41508,39599
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.drop(0, axis=0)
df

In [ ]:
df = df.drop(1, axis=0)
df

In [ ]:
# 刪除多列
df = df.drop(df.index[32:36])
df

In [13]:
df.describe()

,Unnamed: 1,工業及服務業,工業,礦業及土石採取業,石油及天然氣礦業,砂﹑石採取及其他礦業,製造業,食品及飼品製造業,飲料及菸草製造業,紡織業,...,醫療保健及社會工作服務業,醫療保健業,社會工作服務業,藝術﹑娛樂及休閒服務業,創作及藝術表演業,運動﹑娛樂及休閒服務業,其他服務業,個人及家庭用品維修業,美髮及美容美體業,其他個人服務業
count,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,32,32,32,32,32
unique,32,32,32,32,32,32,32,32,32,32,...,32,32,6,32,32,32,32,32,32,32
top,81年,29436,27937,31937,47400,26337,26942,26299,40100,25839,...,35670,35670,-,20463,25183,20366,21485,26239,15106,21441
freq,1,1,1,1,1,1,1,1,1,1,...,1,1,27,1,1,1,1,1,1,1

In [16]:
for col in df.columns:
  print(col)

Unnamed: 1
工業及服務業
工業
礦業及土石採取業
石油及天然氣礦業
砂﹑石採取及其他礦業
製造業
食品及飼品製造業
飲料及菸草製造業
紡織業
成衣及服飾品製造業
皮革﹑毛皮及其製品製造業
木竹製品製造業
紙漿﹑紙及紙製品製造業
印刷及資料儲存媒體複製業
石油及煤製品製造業
化學材料及肥料製造業
其他化學製品製造業
藥品及醫用化學製品製造業
橡膠製品製造業
塑膠製品製造業
非金屬礦物製品製造業
基本金屬製造業
金屬製品製造業
電子零組件製造業
電腦﹑電子產品及光學製品製造業
電力設備及配備製造業
機械設備製造業
汽車及其零件製造業
其他運輸工具及其零件製造業
家具製造業
其他製造業
產業用機械設備維修及安裝業
電力及燃氣供應業
電力供應業
氣體燃料供應業
用水供應及污染整治業
用水供應業
廢水及污水處理業
廢棄物清除業
廢棄物處理業
資源物回收處理及污染整治業
營建工程業
建築工程業
土木工程業
機電﹑管道及其他建築設備安裝業
其他專門營造業
服務業
批發及零售業
批發業
零售業
運輸及倉儲業
鐵路及捷運運輸業
公共汽車客運業
其他汽車客運業
汽車貨運業
海洋水運業
航空運輸業
港埠業
其他運輸輔助業
倉儲業
郵政業
遞送服務業
住宿及餐飲業
住宿業
餐飲業
餐館
其他餐飲業
出版影音及資通訊業
出版業
影片及電視節目業;聲音錄製及音樂發行業
廣播﹑電視節目編排及傳播業
電信業
電腦程式設計﹑諮詢及相關服務業
資訊服務業
金融及保險業
銀行業
信用合作社
農會及漁會信用部
其他金融服務業
人身保險業
財產保險業
其他保險輔助業
證券期貨及金融輔助業
不動產業
不動產開發業
不動產經營及相關服務業
專業﹑科學及技術服務業
法律服務業
會計服務業
企業總管理機構及管理顧問業
建築﹑工程服務及技術檢測﹑分析服務業
研究發展服務業
廣告業及市場研究業
專門設計業
其他專業﹑科學及技術服務業
支援服務業
租賃業
人力仲介業
人力供應業
旅行及其他相關服務業
保全及偵探業
建築物及綠化服務業
行政支援服務業
教育業（不含小學以上各級公私立學校等）
學前教育
教育輔助及其他教育業
醫療保健及社會工作服務業
醫療保健業
社會工作服務業
藝術﹑娛樂及休閒服務業
創作及藝術表演業
運動﹑娛樂及休閒服務業
其他服務業
個人及家庭用品維修業
美髮及美容美體業
其他個人服務業